XML PARSER - Checks for well formed XML.
Project by V Priyan (1100136) and Aravind Sagar (1100104)

1. System Requirements
----------------------
- Operating System: Linux (tested under Ubuntu and Ubuntu-based distributions)
- Bison ver 3.0 or greater.
- flex ver 2.5 or greater.
- gcc ver 4.6 or greater.
- Minimum 1 GHz processor and 1 GB RAM recommended.

2. Compiling and running XML Parser
-----------------------------------
- Precompiled binary a.out is present inside the bin folder, however, compiling from source is recommended.
- Source code can be found under src folder.
- In terminal, navigate to the src folder. xmlscanner.l, xmlparser.y, and symboltable.h are the main source files. Others are generated by flex and bison.
- Run the following commands:
	(i)   flex xmlscanner.l
	(ii)  bison -d xmlparser.y
	(iii) gcc xmlparser.tab.c lex.yy.c
- Executable a.out will be created.

3. Test files
-------------
- Some sample test files can be found inside tests folder. 
- Files in the format c<i> are valid XML files and in the format ic<i> are invalid XML files.
- The files can be given as input to the XML Parser as follows: (assuming that the terminal is open at location src or bin)
	./a.out <../tests/c1

c1 can be replaced with any of the test files inside tests folder.

